language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libasound2-dev ; fi
os:
  - linux
  - osx
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
